[project]
name = "docu-mcp-server"
version = "0.1.0"
description = "MCP Server for interacting with any online developer documentation pages"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.3.4",
]
